=== xolyspirit/library/src/data/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="BookList" type="BookList"/>

   <xs:complexType name="Book">
       <xs:sequence>
           <xs:element name="id" type="xs:long"/>
           <xs:element name="author" type="Author" minOccurs="1" maxOccurs="unbounded"/>
           <xs:element name="name" type="xs:string"/>
           <xs:element name="ISBN" type="xs:int"/>
           <xs:element name="cost" type="xs:double"/>
       </xs:sequence>
   </xs:complexType>

    <xs:complexType name="BookList">
        <xs:sequence>
            <xs:element type="Book" name="Book" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Author">
        <xs:sequence>
        <xs:element name="firstName" type="xs:string"/>
        <xs:element name="lastName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== xolyspirit/library/Books.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<BookList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
<Book>
<id>1</id>
<author>
<firstName>SomeName1</firstName>
<lastName>SomeLastName1</lastName>
</author>
<author>
<firstName>SomeName2</firstName>
<lastName>SomeLastName2</lastName>
</author>
<name>SomeBook1</name>
<ISBN>123456789</ISBN>
<cost>2.5</cost>
</Book>
<Book>
<id>2</id>
<author>
<firstName>SomeName3</firstName>
<lastName>SomeLastName3</lastName>
</author>
<name>SomeBook2</name>
<ISBN>234567891</ISBN>
<cost>3.2</cost>
</Book>
<Book>
<id>3</id>
<author>
<firstName>SomeName4</firstName>
<lastName>SomeLastName4</lastName>
</author>
<name>SomeBook3</name>
<ISBN>23456789</ISBN>
<cost>4.2</cost>
</Book>
</BookList>

=== xolyspirit/library/src/data/Books.xml
<?xml version="1.0" encoding="utf-8"?>
<BookList xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="books.xsd">
    <Book>
        <id>1</id>
        <author>
            <firstName>SomeName1</firstName>
            <lastName>SomeLastName1</lastName>
        </author>
        <author>
            <firstName>SomeName2</firstName>
            <lastName>SomeLastName2</lastName>
        </author>
        <name>SomeBookName</name>
        <ISBN>12345678</ISBN>
        <cost>5.2</cost>
    </Book>
    <Book>
        <id>2</id>
        <author>
            <firstName>SomeName3</firstName>
            <lastName>SomeLastName3</lastName>
        </author>
        <name>SomeBookName2</name>
        <ISBN>234567891</ISBN>
        <cost>5.5</cost>
    </Book>
    <Book>
        <id>3</id>
        <author>
            <firstName>SomeName3</firstName>
            <lastName>SomeLastName3</lastName>
        </author>
        <name>SomeBookName3</name>
        <ISBN>345678912</ISBN>
        <cost>6.5</cost>
    </Book>

</BookList>
